### ISSUE TITLE
`useTextBuffer` Issue with Chat Endpoint

### ISSUE THREAD

**Issue by biowaffeln** [gptlabs/nextjs-openai#8]
I found that when using an OpenAI stream with the "chat" endpoint, we get JSON objects like this:

```js
['{"role":"assistant"}{"content":"This"}', '{"content":" is"}{"content":" an"}', '{"content":" example"}']
```

So when we use useTextBuffer or StreamingTextURL, we end up with these strings instead of plain text.

I came up with a helper function in my project that parses the content out of these objects. Happy to submit a PR for this. Maybe one can add another parameter to useTextBuffer/StreamTextURL, like this: 

```js
useTextBuffer({ 
  url: "api/chat",
  type: "chat" // defaults to "text" or "plaintext"
});
```
 
 Let me know what you think.

**Comment by ctjlewis** [comment]
That would be helpful. I added support for chat day-of and I only realized getting it actually working in production yesterday that there's a need to add newlines to denote multiple events in one chunk and also take the "JSON.parse sum" approach to wait for a full object to come back.

`{ role: "assistant" }\n{ ... }`

But feel free to put a draft PR in and I'll work on it with you. I need to add tests to the lib rather than just doing by hand soon...
